// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg5dPRf8efVMGNjuwB_e3QrTXZFAXSboY',
    appId: '1:403715657150:web:2b67995316eeba4dbfbdef',
    messagingSenderId: '403715657150',
    projectId: 'loginflutter-88f1d',
    authDomain: 'loginflutter-88f1d.firebaseapp.com',
    storageBucket: 'loginflutter-88f1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClj-tfF5rAVPzIcJNjZtDgbqZ4I7HcXLM',
    appId: '1:403715657150:android:089faafc7c2b2565bfbdef',
    messagingSenderId: '403715657150',
    projectId: 'loginflutter-88f1d',
    storageBucket: 'loginflutter-88f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx00zMtIUfkd2uux5ldngoJUVfV-aUKNk',
    appId: '1:403715657150:ios:1f1d2dab9e69071fbfbdef',
    messagingSenderId: '403715657150',
    projectId: 'loginflutter-88f1d',
    storageBucket: 'loginflutter-88f1d.appspot.com',
    iosClientId: '403715657150-g0f9lkbsgfntajkgq6kpk6kt1bl0g9b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx00zMtIUfkd2uux5ldngoJUVfV-aUKNk',
    appId: '1:403715657150:ios:1f1d2dab9e69071fbfbdef',
    messagingSenderId: '403715657150',
    projectId: 'loginflutter-88f1d',
    storageBucket: 'loginflutter-88f1d.appspot.com',
    iosClientId: '403715657150-g0f9lkbsgfntajkgq6kpk6kt1bl0g9b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
